#ifndef KEYS_HPP_INCLUDED
#define KEYS_HPP_INCLUDED

namespace cream {

enum Keys : int
{
    CREAM_KEY_NONE = 0,
    // Group 1
    CREAM_KEY_A,
    CREAM_KEY_B,
    CREAM_KEY_C,
    CREAM_KEY_D,
    CREAM_KEY_E,
    CREAM_KEY_F,
    CREAM_KEY_G,
    CREAM_KEY_H,
    CREAM_KEY_I,
    CREAM_KEY_J,
    CREAM_KEY_K,
    CREAM_KEY_L,
    CREAM_KEY_M,
    CREAM_KEY_N,
    CREAM_KEY_O,
    CREAM_KEY_P,
    CREAM_KEY_Q,
    CREAM_KEY_R,
    CREAM_KEY_S,
    CREAM_KEY_T,
    CREAM_KEY_U,
    CREAM_KEY_V,
    CREAM_KEY_W,
    CREAM_KEY_X,
    CREAM_KEY_Y,
    CREAM_KEY_Z,
    CREAM_KEY_0,
    CREAM_KEY_1,
    CREAM_KEY_2,
    CREAM_KEY_3,
    CREAM_KEY_4,
    CREAM_KEY_5,
    CREAM_KEY_6,
    CREAM_KEY_7,
    CREAM_KEY_8,
    CREAM_KEY_9,
    // Group 2
    CREAM_KEY_ESCAPE,
    CREAM_KEY_ENTER,
    CREAM_KEY_TAB,
    CREAM_KEY_BACKSPACE,
    CREAM_KEY_INSERT,
    CREAM_KEY_DELETE,
    CREAM_KEY_RIGHT,
    CREAM_KEY_LEFT,
    CREAM_KEY_DOWN,
    CREAM_KEY_UP,
    // Group 3
    CREAM_KEY_SPACE,
    // Group 4
    CREAM_KEY_F1,
    CREAM_KEY_F2,
    CREAM_KEY_F3,
    CREAM_KEY_F4,
    CREAM_KEY_F5,
    CREAM_KEY_F6,
    CREAM_KEY_F7,
    CREAM_KEY_F8,
    CREAM_KEY_F9,
    CREAM_KEY_F10,
    CREAM_KEY_F11,
    CREAM_KEY_F12,
    // Group 5
    CREAM_KEY_LEFT_SHIFT,
    CREAM_KEY_LEFT_CONTROL,
    CREAM_KEY_LEFT_ALT,
    // Group 6
    CREAM_KEY_RIGHT_SHIFT,
    CREAM_KEY_RIGHT_CONTROL,
    CREAM_KEY_RIGHT_ALT
};

}  // namespace cream

#endif
